=== AntonioChacon44/LMSGI_Ejercicios/Unidad_04_DTD_XSD/DTD/ejercicios/ejercicios_con_errores/pruebaexamen.dtd
<!ELEMENT fruteria (fruta | precio | localizacion)*>
<!ELEMENT fruta EMPTY>
<!ATTLIST fruta nombre ID #REQUIRED
                caducidad NMTOKENS #REQUIRED
                calorias NMTOKEN #REQUIRED
                conservantes (contiene | noContiene) #FIXED "noContiene">

<!ELEMENT precio (nombre)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST precio precioImportacion NMTOKENS #REQUIRED
                 precioeExportacion NMTOKENS #REQUIRED
                 tipoPago (tarjeta | efectivo) #REQUIRED
                 IVA CDATA #IMPLIED>

<!ELEMENT localizacion (productoNacional, productoExtranjero)>
<!ATTLIST localizacion estado ID #REQUIRED>
<!ELEMENT productoNacional (#PCDATA)*>
<!ELEMENT productoExtranjero (#PCDATA)*>
<!ENTITY  % maduracion "<!ATTLIST localizacion maduracion CDATA #IMPLIED>">
%maduracion;

=== AntonioChacon44/LMSGI_Ejercicios/Unidad_04_DTD_XSD/DTD/ejercicios/ejercicios_con_errores/pruebaexamen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fruteria SYSTEM "pruebaexamen.dtd"[
<!ENTITY excusa  "Esto es una excusa">

]>
<fruteria>
    <fruta nombre="Naranja" caducidad="26-07-2023" calorias="250" conservantes="noContiene" />
    <fruta nombre="Platano" caducidad="01-12-2022" calorias="290" conservantes="noContiene" />
    <fruta nombre="Pera" caducidad="12-11-2022" calorias="120" conservantes="noContiene" />

    <precio precioImportacion="5 euros" precioeExportacion="8 euros" tipoPago="tarjeta">
        <nombre>Naranja</nombre>
    </precio>

    <precio precioImportacion="3 euros" precioeExportacion="7 euros" tipoPago="tarjeta">
        <nombre>Platano</nombre>
    </precio>

    <precio precioImportacion="2 euros" precioeExportacion="2.80 euros" tipoPago="tarjeta">
        <nombre>Pera</nombre>
    </precio>
    
    <localizacion maduracion="Estan maduras" estado="EStados_unidos">
        <productoNacional></productoNacional>
        <productoExtranjero></productoExtranjero>
    </localizacion>

    <localizacion maduracion="Estan maduras" estado="Estados_Unidos">
        <productoNacional></productoNacional>
        <productoExtranjero></productoExtranjero>
    </localizacion>



</fruteria>
